services:
  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:3.2.2
    restart: always
    environment:
      ES_HOST: "10.150.1.87"
      ES_PORT: "9200"
      ES_USER: "elastic"
      ES_PASSWORD: "kkl@#2023@"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./strip.lua:/fluent-bit/etc/strip.lua:ro
      - /etc/docker/logs:/etc/docker/logs:ro
      - fluentbit-state:/fluent-bit/state
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  fluentbit-state:
